### ISSUE TITLE
Addon not reading pressure from Acurite Atlas 733

### ISSUE THREAD

**Issue by jwbernin** [thejeffreystone/hassio_addons#13]
This addon is reading information from my Acurite Atlas 733 correctly, but the barometric pressure reading is not showing up in HASS. As best I can tell, it is not reading this information because there's no configuration for pressure coming through in inHg (inches of mercury), and that seems to be the units the Atlas 733 uses to report pressure.

**Comment by thejeffreystone** [comment]
Thanks for the heads up! 

If that's all it is then it should be an easy fix. 

I'm working on an update now.

**Comment by thejeffreystone** [comment]
Update the code to include a definition for inHG. I dont have a way to test if that solves it though. So let me know if that fixes it.

**Comment by jwbernin** [comment]
Apologies for the delay in response. A little research turned up the interesting fact that the Atlas device doesn't actually measure / broadcast pressure - that sensor is inside the display console, so there's nothing to read from the SDR dongle. That seems to be true of a number of multi-function Atlas devices. Given that, I'm closing this issue as "NOTABUG".
