### ISSUE TITLE
Invalid Add-on repository

### ISSUE THREAD

**Issue by satwiz-md** [thejeffreystone/hassio_addons#2]
WHY ?

**Comment by exeljb** [comment]
the link is incorrect...try this one instead: https://github.com/thejeffreystone/hassio_addons

there's a hyphen ( - ) between hassio & addons when it should be an underscore ( _ )

**Comment by thejeffreystone** [comment]
Thanks for catching that! I just got that updated. 
https://github.com/thejeffreystone/hassio_addons/commit/60128f96c8e2799ca727b339448c487466be84ba
