### ISSUE TITLE
Can't install add-on repository. 

### ISSUE THREAD

**Issue by letnic** [thejeffreystone/hassio_addons#22]
I try to add the add-on repository and I get this error message.
I'm at the latest version of home assistant, supervisor-2021.12.2 and core-2021.12.6

![image](https://user-images.githubusercontent.com/44958574/147525289-17ce6f00-2279-4be4-bef2-10edb614f292.png)

This is what I can see in Supervisor logs 
![image](https://user-images.githubusercontent.com/44958574/147525508-aab4ae0f-1c6d-49f7-b43e-f5f664587ffd.png)

I try to ping google.com and github.com and both of them respond so it's not the internet connection that is in trouble.

Does anyone has same problem ?

**Comment by staniel1881** [comment]
Try this: 
https://github.com/thejeffreystone/hassio_addons

**Comment by letnic** [comment]
Thanks it work. Someone need to update the read me page with the good link.

**Comment by thejeffreystone** [comment]
Readme Updated - bb31c440e728c012c5bee3cdc196ee0fb194d370
