### ISSUE TITLE
WHITELIST_ENABLED & WHITELIST environment variables

### ISSUE THREAD

**Issue by tomdoherty99** [thejeffreystone/hassio_addons#27]
I had to add a couple of environment variables to the docker controls to get the **SDR to Home Assistant (amd64-addon-sdr2mqtt:0.1.9b)** add on to start correctly. 

a) WHITELIST_ENABLE : False
b) WHITELIST : 

Attached a couple of logs. One without the evars and one with.

[without evars.txt](https://github.com/thejeffreystone/hassio_addons/files/8148058/without.evars.txt)
[With evars.txt](https://github.com/thejeffreystone/hassio_addons/files/8148059/With.evars.txt)

**Comment by thejeffreystone** [comment]
Yeah. Was trying to fix something else and broke this... Update should put everything back.

**Comment by thejeffreystone** [comment]
0.1.11b should be working for SDR2MQTT.

**Comment by tomdoherty99** [comment]
Put that in and working well.

**Comment by thejeffreystone** [comment]
I think this is good, so closing. I did found another whitelist bug, working on it now.
