### ISSUE TITLE
usb_open error -1

### ISSUE THREAD

**Issue by rusnak666** [thejeffreystone/hassio_addons#4]
Hi, after updating the home assistant to core-2021.2.2 i get error at the end of log: usb_open error -1
Devices discovered from acurite addon are not working anymore, can i do with this issue something? Thank You

**Comment by staniel1881** [comment]
Hi, yep same issue here currently, love this project Jeff, 
This here might help to sort it out . 
https://github.com/james-fry/hassio-addons/issues/39

**Comment by thejeffreystone** [comment]
Right on. I just updated the code the config for the USB. I think that should fix the issue.

**Comment by thejeffreystone** [comment]
Let me know if you are still seeing issues!

**Comment by rusnak666** [comment]
Hi, Yes, everything is working now! Thank You for the fix, BTW, I Love your addon!

**Comment by thejeffreystone** [comment]
Going to close this, let me know if you see any other issues!
