### ISSUE TITLE
Warnings in Supervisor log

### ISSUE THREAD

**Issue by jkyselak** [thejeffreystone/hassio_addons#5]
I just started getting these warnings in the supervisor log:
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of Acurite to Home Assistant
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Acurite to Home Assistant

**Comment by thejeffreystone** [comment]
I think we have this fixed now.
