### ISSUE TITLE
915 MHz Sensor support

### ISSUE THREAD

**Issue by jkyselak** [thejeffreystone/hassio_addons#8]
Love the addon, just was wondering if it would be possible to make the frequency and sample rate configurable in order to support the LaCrosse sensors for example which almost exclusively use 915 MHz. I looked at the original rtl_433 script and it does support options:
[-f <frequency>] Receive frequency(s) (default: 433920000 Hz) and
[-s <sample rate>] Set sample rate (default: 250000 Hz)

Thanks

**Comment by thejeffreystone** [comment]
I think I will build a version of this that is completely raw so that it will be easier to define the conditions of the addon.

**Comment by thejeffreystone** [comment]
Ok, added a new "add-on" called sdr2mqtt. 

It lets you set the frequency. Just have to set the frequency n the config to -f 915M  instead of -f 433.92M

Let me know if it works. It appears to register the frequecy. Just dont have any devices near me to test.

**Comment by jkyselak** [comment]
Works like a charm with a Lacrosse TH3 sensor @ 915MHz!

Thanks for making the update.

**Comment by thejeffreystone** [comment]
Going to close this, let me know if you see any other issues.

[b2f43a7](https://github.com/thejeffreystone/hassio_addons/commit/b2f43a733e6de6e614efa14298e55ddcd2da145b)
